# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mjs/openai-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mjs/openai-cpp/CPP-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mjs/openai-cpp/CPP-project/CMakeFiles /home/mjs/openai-cpp/CPP-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mjs/openai-cpp/CPP-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 00-showcase

# Build rule for target.
00-showcase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 00-showcase
.PHONY : 00-showcase

# fast build rule for target.
00-showcase/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/00-showcase.dir/build.make examples/CMakeFiles/00-showcase.dir/build
.PHONY : 00-showcase/fast

#=============================================================================
# Target rules for targets named 01-model

# Build rule for target.
01-model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 01-model
.PHONY : 01-model

# fast build rule for target.
01-model/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/01-model.dir/build.make examples/CMakeFiles/01-model.dir/build
.PHONY : 01-model/fast

#=============================================================================
# Target rules for targets named 02-completion

# Build rule for target.
02-completion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 02-completion
.PHONY : 02-completion

# fast build rule for target.
02-completion/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/02-completion.dir/build.make examples/CMakeFiles/02-completion.dir/build
.PHONY : 02-completion/fast

#=============================================================================
# Target rules for targets named 03-edit

# Build rule for target.
03-edit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 03-edit
.PHONY : 03-edit

# fast build rule for target.
03-edit/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/03-edit.dir/build.make examples/CMakeFiles/03-edit.dir/build
.PHONY : 03-edit/fast

#=============================================================================
# Target rules for targets named 04-image

# Build rule for target.
04-image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 04-image
.PHONY : 04-image

# fast build rule for target.
04-image/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/04-image.dir/build.make examples/CMakeFiles/04-image.dir/build
.PHONY : 04-image/fast

#=============================================================================
# Target rules for targets named 05-embedding

# Build rule for target.
05-embedding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 05-embedding
.PHONY : 05-embedding

# fast build rule for target.
05-embedding/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/05-embedding.dir/build.make examples/CMakeFiles/05-embedding.dir/build
.PHONY : 05-embedding/fast

#=============================================================================
# Target rules for targets named 06-file

# Build rule for target.
06-file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 06-file
.PHONY : 06-file

# fast build rule for target.
06-file/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/06-file.dir/build.make examples/CMakeFiles/06-file.dir/build
.PHONY : 06-file/fast

#=============================================================================
# Target rules for targets named 07-fine-tune

# Build rule for target.
07-fine-tune: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 07-fine-tune
.PHONY : 07-fine-tune

# fast build rule for target.
07-fine-tune/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/07-fine-tune.dir/build.make examples/CMakeFiles/07-fine-tune.dir/build
.PHONY : 07-fine-tune/fast

#=============================================================================
# Target rules for targets named 09-instances

# Build rule for target.
09-instances: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 09-instances
.PHONY : 09-instances

# fast build rule for target.
09-instances/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/09-instances.dir/build.make examples/CMakeFiles/09-instances.dir/build
.PHONY : 09-instances/fast

#=============================================================================
# Target rules for targets named 10-chat

# Build rule for target.
10-chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 10-chat
.PHONY : 10-chat

# fast build rule for target.
10-chat/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/10-chat.dir/build.make examples/CMakeFiles/10-chat.dir/build
.PHONY : 10-chat/fast

#=============================================================================
# Target rules for targets named 11-audio

# Build rule for target.
11-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 11-audio
.PHONY : 11-audio

# fast build rule for target.
11-audio/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/11-audio.dir/build.make examples/CMakeFiles/11-audio.dir/build
.PHONY : 11-audio/fast

#=============================================================================
# Target rules for targets named 12-moderation

# Build rule for target.
12-moderation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 12-moderation
.PHONY : 12-moderation

# fast build rule for target.
12-moderation/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/12-moderation.dir/build.make examples/CMakeFiles/12-moderation.dir/build
.PHONY : 12-moderation/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 00-showcase"
	@echo "... 01-model"
	@echo "... 02-completion"
	@echo "... 03-edit"
	@echo "... 04-image"
	@echo "... 05-embedding"
	@echo "... 06-file"
	@echo "... 07-fine-tune"
	@echo "... 09-instances"
	@echo "... 10-chat"
	@echo "... 11-audio"
	@echo "... 12-moderation"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

